### PR TITLE
use local storage events to communicate between peers

### LINKED ISSUE #4: opening index.html via file: does not work on chrome/safari
the communication between simulated peers do work on firefox using `localhost` or `file:`.

for chrome/safari, this only works for `localhost` currently.

check, if we can improve that, otherwise document the issue.

### PR DESCRIPTION
**Pull request by adbenitez**
hopefully this fixes #4

### CODE REVIEW

File: webxdc.js [hunk 1]
```diff
@@ -1,125 +1,82 @@
...
-            var storage = window.localStorage;
-            storage.setItem(testKey, "1");
-            storage.removeItem(testKey);
-            return true;
-        } catch (error) {
-            return false;
+    window.addEventListener('storage', (event) => {
+        if (event.key == null) {
+            window.location.reload();
+        } else if (event.key == updatesKey) {
```
Comment (r10s) [inline webxdc.js:8]:
```suggestion
        } else if (event.key === updatesKey) {
```

iirc, in general, it is advisable in javascript to use the "strict equality" operator, that are three equal signs.

File: webxdc.js [hunk 2]
```diff
@@ -1,125 +1,82 @@
...
-    var localStorageSupported = () => {
-        var testKey = "__xdcTestKey__";
-        try {
-            var storage = window.localStorage;
-            storage.setItem(testKey, "1");
-            storage.removeItem(testKey);
-            return true;
-        } catch (error) {
-            return false;
+    window.addEventListener('storage', (event) => {
```
Comment (r10s) [inline webxdc.js:5]: why is that here and not on top-level as the other added event-listener? if there are no special reasons, i'd keep similar things together.

File: webxdc.js [hunk 3]
```diff
@@ -1,125 +1,82 @@
...
+        if (event.key == null) {
+            window.location.reload();
```
Comment (r10s) [inline webxdc.js:7]: that's a clever thing, to update all views on "Clear Storage" :)

**Review by r10s — APPROVED** [review]
lgtm, only minor suggestions, no blockers.

i also tested - that works with the local file: protocol also on safari now, however, one has still to enable "Develop / Disable Local File Restrictions".

File: webxdc.js [hunk 4]
```diff
@@ -1,125 +1,82 @@
...
+    var styleMenuLink = 'color:#fff; text-decoration: none;';
     var title = document.getElementsByTagName('title')[0];
     if (typeof title == 'undefined') {
         title = document.createElement('title');
         document.getElementsByTagName('head')[0].append(title);
     }
     title.innerText = window.webxdc.selfAddr();
 
-    if (getXdcRoot() === window) {
+    if (window.webxdc.selfName() == "device0") {
```
Comment (ralphtheninja) [inline webxdc.js:71]:
```suggestion
    if (window.webxdc.selfName() === "device0") {
```

File: webxdc.js (hunk 2 above)
Comment (adbenitez) [reply webxdc.js:5]: because updatesKey is secret/private to the webxdc object, I could rework it and use a global const maybe renaming it to xdcUpdatesKey to avoid possible collisions with app's code

Comment (ralphtheninja) [reply webxdc.js:5]: > because updatesKey is secret/private to the webxdc object, I could rework it and use a global const maybe renaming it to xdcUpdatesKey to avoid possible collisions with app's code

Then there's a good reason for it. Keep it as it is for now :smile:

Comment (r10s) [reply webxdc.js:5]: yip, that is a good reason, just keep it, i was just asking :)
